"""initial whatsapp tutor schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-15 16:01:11.938357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone_number_id')
    )
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_wa_id'), 'api_usage', ['wa_id'], unique=False)
    op.create_index('ix_api_usage_wa_id_created_at', 'api_usage', ['wa_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('wa_id', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wa_id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_key'), 'webhook_events', ['event_key'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_wa_id', sa.String(length=64), nullable=False),
    sa.Column('agent_phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_response_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_phone_number_id'], ['agents.phone_number_id'], ),
    sa.ForeignKeyConstraint(['user_wa_id'], ['users.wa_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_phone_number_id'), 'conversations', ['agent_phone_number_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_wa_id'), 'conversations', ['user_wa_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_wa_id', sa.String(length=64), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_wa_id'], ['users.wa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_wa_id'), 'messages', ['user_wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_wa_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_wa_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_phone_number_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_webhook_events_event_key'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_index('ix_api_usage_wa_id_created_at', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_wa_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_table('agents')
    # ### end Alembic commands ###
